name: Coverage
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Coverage
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rspec
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage
